### ISSUE TITLE
`fetchSignUpFormValues()` throws NullPointerException

### ISSUE THREAD

**Issue by phi1ipp** [okta/okta-idx-java#425]
Trying to go with the registration flow but getting the following
```
Exception in thread "main" java.lang.NullPointerException: Cannot invoke "String.length()" because "this.input" is null
	at java.base/java.net.URI$Parser.parse(URI.java:3164)
	at java.base/java.net.URI.<init>(URI.java:623)
	at java.base/java.net.URI.create(URI.java:904)
	at com.okta.commons.http.DefaultRequest.<init>(DefaultRequest.java:59)
	at com.okta.idx.sdk.api.client.BaseIDXClient.enroll(BaseIDXClient.java:257)
	at com.okta.idx.sdk.api.client.IDXAuthenticationWrapper.lambda$fetchSignUpFormValues$21(IDXAuthenticationWrapper.java:704)
	at com.okta.idx.sdk.api.client.AuthenticationTransaction.proceed(AuthenticationTransaction.java:101)
	at com.okta.idx.sdk.api.client.IDXAuthenticationWrapper.fetchSignUpFormValues(IDXAuthenticationWrapper.java:700)
```

Used to work just fine, but after switching the secret for OIDC web application in my tenant I see the above exception. Interaction code flow enabled for the app, allowed in the access policy too.

When running registration from browser js-idx through other application (PKCE SPA), all works fine.

Please advise!

**Comment by arvindkrishnakumar-okta** [comment]
Thanks for reporting this! We'll take a look and get it fixed.

**Comment by phi1ipp** [comment]
@arvindkrishnakumar-okta , figured the issue is application federated broker mode. It was disabled for my app.

Still I think the exception is not informative at all. Would be nice to catch and provide some meaningful message
